# Development profile - for local development
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/terencio_erp
    username: terencio_admin
    password: terencio_admin

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    es.terencio: DEBUG
